Algoritmo "antecessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Leia um valor e escreva seu antecessor
// Autor(a)    : Beatriz
// Data atual  : 21/03/2022
Var
// Seção de Declarações das variáveis 
numero, antecessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número:")
leia(numero)
antecessor <- numero - 1
escreval("O número antecessor é: ",antecessor)
Fimalgoritmo