Algoritmo "sucessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Ler um número e informar seu sucessor
// Autor(a)    : Beatriz
// Data atual  : 21/03/2022
Var
// Seção de Declarações das variáveis 
numero, sucessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número:")
leia(numero)
sucessor <- numero + 1
escreval("O número sucessor é: ",sucessor)
Fimalgoritmo